#!/bin/bash
if [ -z "$(pgrep taffybar)" ]; then
  ~/.cabal/bin/taffybar &
fi

# Network manager, so we don't have to configure wifi at the command line.
if [ -z "$(pgrep nm-applet)" ] ; then
  nm-applet --sm-disable &
fi

# Applet for managing print jobs from the tray.
if [ -z "$(pgrep system-config-printer-applet)" ] ; then
  system-config-printer-applet &
fi

# compmgr
if [ -z "$(pgrep xcompmgr)" ] ; then
  xcompmgr -n &
fi

# zeal
killall -q zeal
zeal &

# Use synapse as our app launcher. (-s: don't display until requested)
if [ -z "$(pgrep synapse)" ] ; then
  synapse -s &
fi

nitrogen --set-zoom-fill ~/Pictures/wallpaper/$(ls ~/Pictures/wallpaper/ |sort -R |tail -1)

TOUCHPAD_ID=`xinput | grep 'Synaptics TouchPad' | cut -f 2 | cut -f 2 -d =`
xinput set-prop $TOUCHPAD_ID "Device Enabled" 0
