#!/bin/bash

# two finger scrolling
synclient EmulateTwoFingerMinW=20
synclient EmulateTwoFingerMinZ=7
synclient VertTwoFingerScroll=1 

# disable border scrolling
synclient VertEdgeScroll=0

# disable tap to click
synclient TapButton1=0 TapButton2=0 TapButton3=0

# increase coasting speed
synclient CoastingSpeed=40

# minimize right click area
synclient BottomEdge=600
synclient RightEdge=1080
synclient RightButtonAreaLeft=560 # right edge = 1536, 120r = right client
synclient RightButtonAreaTop=500   # bottom edge = 852

# disable touchpad clicks when typing
if [ -z "$(pgrep syndaemon)" ] ; then
    syndaemon -t -d
fi