#! /bin/sh


# set the window manager name to "trick" java apps to render correctly
dunst &
wmname LG3D &
compton &
sxhkd &
~/.config/polybar/launch.sh &
# yabar &

# make things homely
feh --randomize --bg-fill ~/images/*
wal --theme base16-gruvbox-hard

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap           4
bspc config top_padding          44
bspc config bottom_padding       0
bspc config left_padding         2
bspc config right_padding        2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocole false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a jetbrains-studio desktop='^2' state=floating border=off follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a code-oss desktop='^1'
bspc rule -a Sublime_text desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
