#! /bin/sh
bspc config border_width        1
bspc config window_gap          0

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

# workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# Color of the border of an urgent window.
bspc config urgent_border_color  "red"
bspc config focused_border_color "#A1CD4C"
bspc config active_border_color  "#A1CD4C"
bspc config normal_border_color  "#333333"
bspc config presel_border_color  "#72A2EE"

# bar configuration
# bspc config top_padding 30

# window rules
bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Sublime_text desktop=^2 follow=on
bspc rule -a Google-chrome-stable desktop=^3 follow=on
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
