#! /bin/sh

#
# my bspm keys

alt + shift + f
	bspc desktop -l next

alt + shift + c
	bspc window -c

alt + Return
	bspc window -s biggest

alt + {_,shift + }{1-9,0}
	bspc {desktop -f,window -d} ^{1-9,10}

#
# stuff i'm not using yet

alt + b
	bspc desktop -B

alt + {s,f}
	bspc window -t {floating,fullscreen}

alt + {o,i}
	bspc control --record-history off; \
	bspc window {older,newer} -f; \
	bspc control --record-history on

alt + y
	bspc window -w last.manual

alt + {_,shift + }Tab
	bspc window -f {next,prev}

alt + {comma,period}
	bspc desktop -C {backward,forward}

alt + bracket{left,right}
	bspc desktop -f {prev,next}

alt + ctrl + {h,j,k,l}
	bspc window -p {left,down,up,right}

alt + ctrl + {_,shift + }space
	bspc {window -p cancel,desktop -c}

alt + {h,j,k,l}
	bspc window -e {left -10,down +10,up -10,right +10}

alt + shift + {h,j,k,l}
	bspc window -e {right -10,up +10,down -10,left +10}

alt + ctrl + {1-9}
	bspc window -r 0.{1-9}

~button1
	bspc pointer -g focus

alt + button{1-3}
	; bspc pointer -g {move,resize_side,resize_corner}

alt + @button{1-3}
	bspc pointer -u

## disabled rlues

#alt + {_,shift + }{h,j,k,l}
#	bspc window -{f,s} {left,down,up,right}

#alt + {grave,Tab}
#	bspc {window,desktop} -f last

#alt + apostrophe
#	bspc window -s last

#
# wm independent hotkeys
#

alt + shift + Return
	roxterm

alt + p
	synapse

# make sxhkd reload its configuration files:
alt + q
	pkill -USR1 -x sxhkd

alt + shift + q
	bspc quit
